(add-hook 'lisp-mode #'evil-cleverparens-mode)
(add-hook 'emacs-lisp-mode #'evil-cleverparens-mode)
(add-hook 'clojure-mode #'evil-cleverparens-mode)
(add-hook 'clojurec-mode #'evil-cleverparens-mode)
(add-hook 'clojurex-mode #'evil-cleverparens-mode)
(add-hook 'clojurescript-mode #'evil-cleverparens-mode)
